### ISSUE TITLE
Grafana - mysql

### ISSUE THREAD

**Issue by ruchan-ziya** [OpenSTEF/openstef-reference#23]
After setting up the container tst_icarus database is set up and accessible via phpMyAdmin. But Graphana does not have tst_icarus as a configured DataSource. And I could not set Graphana to connect to the database. 

![image](https://github.com/OpenSTEF/openstef-reference/assets/133773571/887b347d-c53e-4cc4-b4e9-54c6f3d9ee29)

The container terminal displays: 

```openstef-grafana               | logger=tsdb.mysql t=2023-05-19T07:59:07.819527312Z level=error msg="Query error" err="dial tcp 127.0.0.1:3306: connect: connection refused"```

**Comment by gecube** [comment]
Hi @ruchan-ziya 
is the issue still actual?

**Comment by gecube** [comment]
o.k. I checked and really mysql password is not properly added to grafana.

**Comment by gecube** [comment]
fixed via #37

**Comment by ruchan-ziya** [comment]
Still getting an error and I still see the tst_icarus is there in phpMyAdmin... Maybe it is me?  

openstef-grafana               | logger=tsdb.mysql t=2024-09-25T11:37:35.394429832Z level=error msg="Query error" err="dial tcp [::1]:3306: connect: connection refused"
openstef-grafana               | logger=context userId=1 orgId=1 uname=admin t=2024-09-25T11:37:35.394504706Z level=info msg="Request Completed" method=GET path=/api/datasources/uid/cdyyl940ws074b/health stat

![image](https://github.com/user-attachments/assets/4ef53e6c-7a52-445b-9de7-17a6e086ca7d)

**Comment by gecube** [comment]
@ruchan-ziya did you try to start from scratch? I will be able to check the deployment today later. I am using docker desktop on Mac OS (MacBook Pro 2019 2,6 GHz 6-Core Intel Core i7) if it's important.

**Comment by ruchan-ziya** [comment]
Yes, from scratch... I tested on a Win11 Docker Desktop.

**Comment by gecube** [comment]
worked for me on M1 after restart of `influxdb-configurator`

<img width="1510" alt="Screenshot 2024-09-25 at 15 43 29" src="https://github.com/user-attachments/assets/1fd4ff99-8c30-4e51-afd4-6e67c6b9c8ed">
